use_frameworks!

target 'UIViewUseful_Example' do
	pod 'UIViewUseful', :path => '../'

	target 'UIViewUseful_Tests' do
		inherit! :search_paths

		pod 'Quick', '~> 1.0.0'
		pod 'Nimble', '~> 6.0'
		pod 'FBSnapshotTestCase'
		pod 'Nimble-Snapshots'
	end
end
